- name: "wait each server"
  hosts: deploy
  tasks:
   - wait_for:
       host: "{{ mgmt_ip }}"
       port: 8181
       state: started
       delay: 10
       timeout: 40

   - debug:
       msg: "cluster IPs {{ onos_cluster }} "
   - name: remove known hosts
     shell: rm -rf ~/.ssh/known_hosts

   - name: loging to generate ssh-key
     shell: sshpass -p karaf ssh  -o 'StrictHostKeyChecking no' -p 8101 karaf@{{ mgmt_ip }} ls
     #ignore_errors: true
